### ISSUE TITLE
Test mark now activity failed

### ISSUE THREAD

**Issue by Billy4195** [SWLBot/electronic-blackboard#138]
#128 Add the test mark now activity, but seems that it will failed at sometime.
While the #137 Fix this problem, but I think the behavior of mark_now_activity() is as its function name, which just marks the current displaying target to `is_used`. 
It shouldn't be seen as failed, if there is no target current displaying, because the function only handles the current displaying target.

**Comment by icecat2012** [comment]
Yes, we should reconsider 'no schedule' may not treat as fail. But we need to trace code carefully before modify the function directly. I afraid it may cause a chain errors.

**Comment by Billy4195** [comment]
The mark_now_activity only uses once in the arrange_schedule.py you can check it yourself

**Comment by icecat2012** [comment]
Done.

**Comment by Billy4195** [comment]
Thanks!
