### ISSUE TITLE
load schedule return image but file field is undefined

### ISSUE THREAD

**Issue by Billy4195** [SWLBot/electronic-blackboard#26]
After setup the environment.then upload two image for display 
and it may sometimes load schedule function return file_type is "image"
but the file field is "undefined"

**Comment by Billy4195** [comment]
I found that I forgot to change the path in setting.txt,
but the still problem is that if I only upload one image to the whole system,
it will still return undefined image data

**Comment by icecat2012** [comment]
處理方式同 #15 
加入判斷~
當回傳 result == fail && error == no schedule時
保持顯示原本的 ( board不切換到下一張圖 )
